### ISSUE TITLE
[TV프로그램, 영화] TV프로그램과 영화 메뉴 클릭 시 각 페이지에 대표 포스터와 로고가 표시되도록 변경

### ISSUE THREAD

**Issue by joanjang** [je0489/netflix-clone#4]
## Summary

V프로그램과 영화 메뉴 클릭 시 각 페이지에서 대표 포스터와 로고가 표시되도록 front-end 변경

## How to reproduce
1. TV 프로그램 또는 영화 메뉴를 클릭합니다.
\> 화면이 매우 밋밋함

> AS-IS
<img width="1280" alt="as-is_screen" src="https://user-images.githubusercontent.com/10413702/147381374-6ef98343-99f4-435d-bbcb-6a19e9956bbe.png">

## Task List
- [x] Details 페이지에서 사용한 포스터 이미지를 별도의 컴포넌트로 빼기
- [x] 공통 컴포넌트를 사용하도록
- [x] 각 페이지에 맞게 style 구현 (최대한 공통 style로 묶을 수 있도록)

**Comment by joanjang** [comment]
> TO-BE

<img width="1277" alt="movie-page_TOBE" src="https://user-images.githubusercontent.com/10413702/147408487-b6960885-2412-42da-897f-aa888e0ce3a6.png">
