### ISSUE TITLE
[부가기능] 반응형 웹 디자인 적용

### ISSUE THREAD

**Issue by joanjang** [je0489/netflix-clone#9]
## How to reproduce
1. 개발자 도구에서 모바일용으로 변경한 후 확인합니다.

## Task List
- [x] Header 반응형 적용
- [x] Home 반응형 적용
- [ ] Section 반응형 적용
- [ ] Details 반응형 적용
